### ISSUE TITLE
Locate/create a point shapefile for bike parking in Mountain View

### ISSUE THREAD

**Issue by aprilwebster** [aprilwebster/bicycling_advocacy#1]
### Description
The City of Mountain View has a [static bike parking map](https://www.mountainview.gov/civicax/filebank/blobdload.aspx?BlobID=15004).  A shapefile with points and metadata would be far more useful, easier to maintain and could be used in generating new maps that integrates other spatial data layers (e.g., bike route line data, points of interest point data, etc).  Moreover, a shapefile could be converted to gml/kml and uploaded to a Google Map that would be more available to the general public.

### Tasks
- [ ] Contact Ria Lo at City of Mountain View to ask if they have shapefile
- [ ] If no shapefile is available, collect the data and create a shapefile using QGIS.
- [ ] Figure out how best to keep this shapefile current - would this involve passing it along to the City for ownership?
- [ ] Figure out how to determine the difference between private and public bike parking.

**Comment by aprilwebster** [comment]
#### December 17, 2020
- sent email to Ria Lo at the City of Mountain View to see if the City has this data available
