### ISSUE TITLE
Research support for senior bike education in Mountain View

### ISSUE THREAD

**Issue by aprilwebster** [aprilwebster/bicycling_advocacy#3]
### Description
Most bike education efforts in the Bay area to date have been focussed on children.  However, if we hope to move the needle on more widespread adoption of bicycling as a viable method of transportation, other demographics will need to be targeted.  Bicycling is one of the best options for staying active and healthy for seniors, particularly those with any sort of chronic joint issues.

### Tasks
- [ ] Research studies that have been done re the benefits of bicycling for seniors
- [ ] Research studies that have been done re the need for bicycling education for seniors
- [ ] Research collisions and accidents in the Bay area (and Mountain View) involving senior bicyclists
